# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ntJN9q3pMkmBHjXGVpN_WTpSuFTrJI07
"""

import json
def options():
    print("\nContact Book Options:")
    print("1. Add a Contact")
    print("2. View Contacts")
    print("3. Search for a Contact")
    print("4. Exit")
    select= input("Enter your select(1/2/3/4): ")
    return select
# Function to load contacts from a file
def load():
    try:
        with open("contacts.txt", "r") as file:
            contacts = json.load(file)
    except FileNotFoundError:
        contacts = {}
    return contacts

# Function to save contacts to a file
def save(contacts):
    with open("contacts.txt", "w") as file:
        json.dump(contacts, file,indent=2)

# Function to add a contact
def add(contacts):
    name = input("Enter the name: ")
    phone = input("Enter the phone number: ")
    email = input("Enter the email: ")
    birthday = input("Enter the birthday: ")
    address = input("Enter the address: ")

    contacts[name] = {"phone": phone, "email": email, "birthday":birthday, "address":address}
    print(f"Contact '{name}' added successfully!")

# Function to view all contacts
def view(contacts):
    if not contacts:
        print("No contacts found.")
    else:
        print("Contacts:")
        for name, info in contacts.items():
            print(f"Name: {name}")
            print(f"Phone: {info['phone']}")
            print(f"Email: {info['email']}")
            print(f"Birthday: {info['birthday']}")
            print(f"Address: {info['address']}")
            print("                      ")

# Function to search for a contact
def search(contacts):
    name = input("Enter the name to search: ")
    if name in contacts:
        info = contacts[name]
        print(f"Name: {name}")
        print(f"Phone: {info['phone']}")
        print(f"Email: {info['email']}")
        print(f"Birthday: {info['birthday']}")
        print(f"Address: {info['address']}")
    else:
        print(f"Contact '{name}' not found.")

# Main program loop
def main():
    contacts = load()

    while True:
        option= options()

        if option == "1":
            add(contacts)
        elif option == "2":
            view(contacts)
        elif option == "3":
            search(contacts)
        elif option == "4":
            save(contacts)
            print("Exiting Contact Book. Contacts saved.")
            break
        else:
            print("Invalid option. Please enter a valid option (1/2/3/4).")

if __name__ == "__main__":
    main()